default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: enda
  pool: 5
  username: root
  password: ''
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
